#ifndef TOKEN_KIND_ENUM
#define TOKEN_KIND_ENUM(...)
#endif

TOKEN_KIND_ENUM(Begin)
TOKEN_KIND_ENUM(End)
TOKEN_KIND_ENUM(If)
TOKEN_KIND_ENUM(Then)
TOKEN_KIND_ENUM(While)
TOKEN_KIND_ENUM(Do)
TOKEN_KIND_ENUM(Var)
TOKEN_KIND_ENUM(Procedure)
TOKEN_KIND_ENUM(Call)
TOKEN_KIND_ENUM(Add)
TOKEN_KIND_ENUM(Sub)
TOKEN_KIND_ENUM(Mul)
TOKEN_KIND_ENUM(Div)
TOKEN_KIND_ENUM(Equal)
TOKEN_KIND_ENUM(NotEqual)
TOKEN_KIND_ENUM(Assign)
TOKEN_KIND_ENUM(Int)
TOKEN_KIND_ENUM(Identifier)

#undef TOKEN_KIND_ENUM