#ifndef TOKEN_KEYWORD
#define TOKEN_KEYWORD(X)
#endif

#ifndef TOKEN_PUNCTUATOR
#define TOKEN_PUNCTUATOR(X, Y)
#endif

TOKEN_KEYWORD(begin)
TOKEN_KEYWORD(end)

TOKEN_KEYWORD(if)
TOKEN_KEYWORD(then)
TOKEN_KEYWORD(else)

TOKEN_KEYWORD(while)
TOKEN_KEYWORD(do)

TOKEN_KEYWORD(var)
TOKEN_KEYWORD(procedure)
TOKEN_KEYWORD(call)
TOKEN_KEYWORD(const)
TOKEN_KEYWORD(odd)
TOKEN_KEYWORD(read)
TOKEN_KEYWORD(write)

TOKEN_PUNCTUATOR(plus, "+")
TOKEN_PUNCTUATOR(minus, "-")
TOKEN_PUNCTUATOR(star, "*")
TOKEN_PUNCTUATOR(slash, "/")

TOKEN_PUNCTUATOR(equal, "=")
TOKEN_PUNCTUATOR(less, "<")
TOKEN_PUNCTUATOR(lessequal, "<=")
TOKEN_PUNCTUATOR(greater, ">")
TOKEN_PUNCTUATOR(greaterequal, ">=")

TOKEN_PUNCTUATOR(l_paren, "(")
TOKEN_PUNCTUATOR(r_paren, ")")
TOKEN_PUNCTUATOR(l_brace, "{")
TOKEN_PUNCTUATOR(r_brace, "}")

TOKEN_PUNCTUATOR(semi, ";")
TOKEN_PUNCTUATOR(comma, ",")
TOKEN_PUNCTUATOR(colonequal, ":=")

#undef TOKEN_KEYWORD
#undef TOKEN_PUNCTUATOR